name: Docker Buil/Push, SCITT Register Synsation Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DATATRAILS_CLIENT_ID: ${{ secrets.DATATRAILS_CLIENT_ID }}
  DATATRAILS_SECRET: ${{ secrets.DATATRAILS_SECRET }}
  SYNSATION_SIGNING_KEY: ${{ secrets.SYNSATION_SIGNING_KEY }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | 
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Create buildOutput Directory
        run: |
          mkdir -p ./buildOutput/
      - name: save-keys
        env:
          SIGNING_KEY: ${{ env.SYNSATION_SIGNING_KEY }}
        shell: bash
        run: |
          echo "$SIGNING_KEY" >> ./synsation.pem
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ env.DOCKER_HUB_USER}}
          dockerhub-password: ${{ env.DOCKER_HUB_TOKEN }}
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          sarif-file: "./buildOutput/docker-scout-sarif.json"
          summary: true
      - name: Register Docker Scout Output as a SCITT Signed Statement
        id: register-scitt-signed-statement
        uses: datatrails/scitt-action@v0.3.7.40
        with:
          scitt-client_id: ${{ env.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ env.DATATRAILS_SECRET }}
          feed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          payload: "./buildOutput/docker-scout-sarif.json"
          content-type: "application/vnd.docker.scout+json"
          signing-key-file: "./synsation.pem"
          issuer: "synsation.io"
      - name: Generate SPDX SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b ./buildOutput -bc . -pn synsation-web -pv 1.0.0 -ps synsation-org -nsb https://synsation.io -V Verbose
      - name: Register SPDX as a SCITT Signed Statement
        id: register-spdx-scitt-signed-statement
        uses: datatrails/scitt-action@v0.3.7.40
        with:
          scitt-client_id: ${{ env.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ env.DATATRAILS_SECRET }}
          feed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          payload: "./buildOutput/_manifest/spdx_2.2/manifest.spdx.json"
          content-type: "application/spdx+json"
          signing-key-file: "./synsation.pem"
          issuer: "synsation.io"
      - name: Create Output Directory
        # SPDX automatically creates the _manifest sub directories.
        # CycloneDX assumes the current directory
        # Creating a cyclonedx subdir, in addition to the ./buildOutput for SPDX
        run: |
          mkdir -p ./buildOutput/_manifest/cyclonedx/
      - name: Generate CycloneDX SBOM for Python
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./requirements.txt
          output: ./buildOutput/_manifest/cyclonedx/cyclone-dx.sbom.json
          format: json
      - name: Register CylconeDX as a SCITT Signed Statement
        id: register-cyclonedx-signed-statement
        uses: datatrails/scitt-action@v0.3.7.40
        with:
          scitt-client_id: ${{ env.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ env.DATATRAILS_SECRET }}
          feed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          content-type: "application/vnd.cyclonedx+json"
          payload: "./buildOutput/_manifest/cyclonedx/cyclone-dx.sbom.json"
          signing-key-file: "./synsation.pem"
          issuer: "synsation.io"
      - name: Create Compliance Statement
        # SPDX automatically creates the _manifest sub directories.
        # CycloneDX assumes the current directory
        # Creating a cyclonedx subdir, in addition to the ./buildOutput for SPDX
        run: |
          echo '{"compliance.42":"true","software.eol":"2025-03-15"}' >> ./buildOutput/attestation.json
      - name: Register SPDX as a SCITT Signed Statement
        id: register-compliance-scitt-signed-statement
        uses: datatrails/scitt-action@v0.3.7.40
        with:
          scitt-client_id: ${{ env.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ env.DATATRAILS_SECRET }}
          feed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          payload: "./buildOutput/attestation.json"
          content-type: "application/vnd.unknown.attestation+json"
          signing-key-file: "./synsation.pem"
          issuer: "synsation.io"
      - name: cleanup-keys
        shell: bash
        run: |
          rm ./synsation.pem
