name: SCITT Register Statements

on:
  push:
    branches: [ "main" ]

jobs:
  register-scitt-statements:
    runs-on: ubuntu-latest
    name: Register SCITT Signed Statement
    steps:
      - name: create-payload
        shell: bash
        run: |
          echo '{"FOO":"BAR"}' >> ./payload.json
      - name: save-keys
        env:
          SIGNING_KEY: ${{ secrets.SYNSATION_SIGNING_KEY }}
        shell: bash
        run: |
          echo "$SIGNING_KEY" >> ./synsation.pem
      - name: Register SCITT Signed Statement
        id: register-scitt-signed-statement
        uses: datatrails/scitt-action@v0.3.7.39
        with:
          scitt-client_id: ${{ secrets.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ secrets.DATATRAILS_SECRET }}
          feed: ${{ github.repository }}:v0.1
          payload: "./payload.json"
          signing-key-file: "./synsation.pem"
          issuer: "synsation.io"
      - name: cleanup-keys
        shell: bash
        run: |
          rm ./synsation.pem
  